<?php
	/*
	Homework 6: AJAX
	
	For homework 6, your task is to create a web page which uses an AJAX request to dynamically insert data into a database and refresh the visualization of that data on the page without having the user to reload the page. It is up to you to decide what type of form data to use and how to visualize it (e.g., using a table, or a chart, etc.). For examples, see Lectures 20, 21 and 31. Your page of course has to be substantially different from these examples. Finally, your page should utilize 2 different kinds of widgets or interactions that are implemented in the jQuery UI library (http://jqueryui.com/). Add an about section to the page where you briefly describe what your page does and which jQuery UI widgets or interactions it utilizes. 
	
	[8 pts] Working page
	[1 pt] Code readability and commenting
	[1 pt] Use CSS to make the page look nice
	
	EXTRA CREDIT
	
	[ 1 pt ] Use custom CSS styling for the jQuery widget you are using (e.g., style your own accordion, tooltip, etc.)
	[ 2 pt ] Allow the user to delete an item from the database using AJAX (i.e., without loading the page). Upon deletion form the database, the item should also disappear from the page (you can do that using jQuery .hide() function)
	
	*/
?>

<?php
include 'includes/constants/dbc.php';

//INSERT SUBMITTED INFORMATION TO INQUIRY TABLE
if($_POST and $_GET) //Check for post data
{
	if ($_GET['cmd'] == 'add'){
	
		//Assign variables and sanitize POST data
		$customer = mysql_real_escape_string($_POST['customer']);
		$email = mysql_real_escape_string($_POST['email']);
		$club = mysql_real_escape_string($_POST['club']);
		$shaft = mysql_real_escape_string($_POST['shaft']);
		$subscribe = $_POST['subscribe']; //The value is 'yes' or 'no' only and no need to sanitize
		$comment = mysql_real_escape_string($_POST['comment']);
		$quantity = preg_replace('#[^0-9]#', '', $_POST['quantity']); //get rid of letters except numbers
	 
		//Build a query statement for insertion
		$query = "INSERT INTO ".TABLE_INQUIRIES."(customer, email, club, shaft, quantity, subscribe, comment, time) VALUES ('".$customer."', '".$email."', '".$club."', '".$shaft."', '".$quantity."', '".$subscribe."', '".$comment."', now());";
		mysql_query($query) or die(mysql_error());
		
		//After the $_POST data is processed, we use the exit() function because we don't need to actually show the page as the request is made in the background
		exit();
	}
}

//LOAD PRODUCT INFORMATION FROM PRODUCT TABLE
function load_product_details()
{
    //the variable $build holds the HTML content that is generated by the function
	$build = '';
	
	//set up a query and execute it
	//pull out necessary data from the table and sort descending by product name
	$query = "SELECT product_id, club, details FROM ".TABLE_PRODUCTS." ORDER BY club DESC"; 
    $result = mysql_query($query) or die(mysql_error());
    
	if(mysql_num_rows($result) == 0)
    {
		//if there is no data returned, show below message
		$build .= "<p><b>No product found.</b></p>";
    }
    else
    {
        while($row = mysql_fetch_array($result))
        {
			//wrap the entry by HTML
            $build .= "<h3 class=\"product_title\">".$row['club']."</h3>";
			$build .= "<div>";
            $build .= "<p class=\"product_image\"><img src=\"images/".$row['product_id'].".jpg\" align=\"left\" hspace=\"10\" /></p>";
            $build .= "<p class=\"product_details\"><b>Details: </b><br>".$row['details']."</p>"; 		
            $build .= "</div>";
        }
    }
    return $build;
}

?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Subscription Form with AJAX</title>
		<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
		<script src="//code.jquery.com/jquery-1.10.2.js"></script>
		<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
		<link rel="stylesheet" href="css/jdm.css">
		<script>
		//Function which gets executed when the document is loaded
		$(function()
		{

			//JQUERY UI AUTO-COMPLETION for CLUBs

			//Define an array holding the strings that will be used for auto-completion in the club field.
			var availableClubs = [ ];
			
			$.ajax(
				{
					type: "POST",
					url: "generate_club.php", 
					data: "",
					success: function(response)
					{
						
						/* use JSON's function to parse the response */
						var parsed_response = JSON.parse(response);
						
						/* retrieve the club array that is part of the response. */
						availableClubs = parsed_response.club;
						
						/* select the HTML element with id="club" and call the autocomplete() function from the jquery UI library */
						$( "#club" ).autocomplete({
							source: availableClubs
						});
					}
				}
			);

			//JQUERY UI AUTO-COMPLETION for SHAFTS
			
			//define an array to hold shaft string
			var availableShafts = [ ];
			
			$.ajax(
				{
					type: "POST",
					url: "generate_shaft.php", 
					data: "",
					success: function(response)
					{
						
						/* use JSON's function to parse the response */
						var parsed_response = JSON.parse(response);
						
						/* retrieve the shaft array that is part of the response. */
						availableShafts = parsed_response.shaft;
						
						/* select the HTML element with id="shaft" and call the autocomplete() function from the jquery UI library */
						$( "#shaft" ).autocomplete({
							source: availableShafts
						});
					}
				}
			);

			//PROCESS FORM SUBMISSION & PASS IT ON TO PHP
			$(".submit").click(function()
			{
				
				//create variables to store the data entered into the form
				var customer = $("#customer").val();
				var email = $("#email").val();     
				var club = $("#club").val();     
				var shaft = $("#shaft").val();
				var quantity = $("#quantity").val();
				var comment = $("#comment").val();
			
				/* what if a customer uncheck the subscription box?*/
				if(document.getElementById("subscribe").checked){
					var subscribe = 'yes';
				} else {
					var subscribe = 'no';
				}
					
				//Check for empty values
				if(customer == '' || email == '' || club == '' || shaft == '' || quantity == '')
				{
					//show the html error message where div.error if there is empty field
					$('.error').fadeIn(400).show().html('Please fill required fields.'); 
				}
				else
				{
					//construct the data string to insert the table	
					var datastring = "customer=" + customer + "&email=" + email + "&club=" + club + "&shaft=" + shaft + "&quantity=" + quantity 
					+ "&subscribe=" + subscribe +"&comment=" + comment;
		 
					/* AJAX request. The request is made to $_SERVER['PHP_SELF']
					The request is handled by checking for $_POST data (line 5)	*/
					$.ajax( 
						{
						type: "POST",
						url: "<?php echo $_SERVER['PHP_SELF']; ?>?cmd=add", 
						data: datastring,
						success: function()
							{
								$('#customer').val(''); //Clear out val from text box
								$('#email').val(''); //Clear out val from text box
								$('#club').val(''); //Clear out val from text box
								$('#shaft').val(''); //Clear out val from text box
								$('#quantity').val(''); //Clear out val from text box
								$('#comment').val(''); //Clear out val from text box
								//$('.success').fadeIn(2000).show().html('Thanks ' +customer + ', your request has been submitted successfully!').fadeOut(6000); //Show, then hide success msg
								$('.error').fadeOut(2000).hide(); //If showing error, fade out
								
								var thanks = "Thank you, " + customer + " for your interest!<br>"
								thanks += "Your quote for " + club + " with " + shaft + " shaft is on the way." 
								
								$(function() {
									$( "#success" ).dialog().html(thanks);
								});
								
								//every time user submit information, it load all the messages and show them
								//$("#load_msgs").fadeIn(400).show().load('get_msg.php');
				 
							}
						}
					);
				}
				
				//return false to prevent reloading page
				return false;
			});
			
			//JQUERY UI ACCORDION (pre-defined function) used for product details
			$(function() {
				$( "#accordion" ).accordion();
			});

			//JQUERY UI BUTTON (pre-defined function)
			$( "input[type=submit], button" )
				.button()
				.click(function( event ) {
				event.preventDefault();
			});
		});
		</script>
	</head>
	<body>
		<!-- left container -->
		<div class="container-left">
			<!-- jquery ui accordion -->
			<div id="accordion">
			<?php
				//show product details HTML which is generated by the function
				echo load_product_details();
			?>
			</div>
		</div>
		<!-- container on the right -->	
		<div class="container-right">
			<!-- quote form -->
			<form method="post" name="form" id="quote_form">
				<!-- jquery ui auto-complete for club -->
				<div class="ui-widget">
					<label for="club">Clubs: </label>
					<input id="club">
				</div>
				<!-- jquery ui auto-complete for shaft -->
				<div class="ui-widget">
					<label for="shaft">Shafts: </label>
					<input id="shaft">
				</div>
				<p><label>Quantity : </label>
				<input type="text" id="quantity" name="quantity" /></p>
				<p><label>Full Name: </label>
				<input type="text" id="customer" name="customer" /></p>
				<p><label>Email Address: </label>
				<input type="text" id="email" name="email" /></p>
				<p><label>Comment: </label>
				<textarea name="text" id="comment" rows="5" cols="35"></textarea></p>
				<input type="checkbox" id="subscribe" name="subscribe" value="yes" checked>Subscribe Newsletter
				<p><button type="submit" class="submit" value="submit">Get A Quote!</button></p>
			</form>
			<!-- display error or success message -->
			<p class="error" style="display:none;"></p>
			<div id="success" title="Request Success!"></div>
			<!--<div id="load_msgs" style="display:none;border-top: 1px solid #ccc;"></div>-->
		</div>
	</body>
</html>