<?php
include 'includes/constants/dbc.php';

//function which returns all stored entries wrapped up in HTML code
function load_product_details()
{
    //the variable $build holds the HTML content that is generated by the function
	$build = '';
	
	//set up a query and execute it
	$query = "SELECT product_id, club, details FROM ".TABLE_PRODUCTS." ORDER BY id DESC";
    $result = mysql_query($query) or die(mysql_error());
    
	if(mysql_num_rows($result) == 0)
    {
		$build .= "<p><b>No product found.</b></p>";
    }
    else
    {
        while($row = mysql_fetch_array($result))
        {
			//generated the entory
            $build .= "<h3 class=\"product_title\">".$row['club']."</h3>";
			$build .= "<div>";
            $build .= "<p class=\"product_image\"><img src=\"images/".$row['product_id'].".jpg\">";
            $build .= "<p class=\"product_details\"><b>Details: </b>".$row['details']."</p>"; 		
            $build .= "</div>";
        }
    }
    return $build;
}

?>
	
<html lang="en">
<head>
<meta charset="utf-8">
<title>Product Details with jQuery UI Accordion</title>
<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script>
	//jquery_ui pre-defined function
	$(function() {
		$( "#accordion" ).accordion();
	});
</script>
</head>
<body>
<div id="accordion">
<?php
echo load_product_details();
?>
</div>
</body>
</html>