<?php
require 'includes/constant/config.inc.php';
return_meta("Get A Quote Now!");
?>
	
<script>
	//Function which gets executed when the document is loaded
	$(function()
	{

		/*** JQUERY UI AUTO-COMPLETION ***/

		//define an array to hold club string
		var availableClubs = [ ];
		
		$.ajax(
			{
				type: "POST",
				url: "includes/constant/generate_club.php", 
				data: "",
				success: function(response)
				{
					
					/* use JSON's function to parse the response */
					var parsed_response = JSON.parse(response);
					
					/* retrieve the club array that is part of the response. */
					availableClubs = parsed_response.club;
					
					/* select the HTML element with id="club" and call the autocomplete() function from the jquery UI library */
					$( "#club" ).autocomplete({
						source: availableClubs
					});
				}
			}
		);
	
		//define an array to hold shaft string
		var availableShafts = [ ];
		
		$.ajax(
			{
				type: "POST",
				url: "includes/constant/generate_shaft.php", 
				data: "",
				success: function(response)
				{
					
					/* use JSON's function to parse the response */
					var parsed_response = JSON.parse(response);
					
					/* retrieve the shaft array that is part of the response. */
					availableShafts = parsed_response.shaft;
					
					/* select the HTML element with id="shaft" and call the autocomplete() function from the jquery UI library */
					$( "#shaft" ).autocomplete({
						source: availableShafts
					});
				}
			}
		);


		/*** JQUERY UI ACCORDION (pre-defined function) used for product details ***/
		$(function() {
			$( "#accordion" ).accordion();
		});

		/*** JQUERY STICKY DIV W/ SCROLL ***/
		//http://www.pixelbind.com/make-a-div-stick-when-you-scroll/
		//http://www.pixelbind.com/examples/stick-a-div/2/
		$(document).ready(function() {
			var s = $("#sticker");
			var pos = s.position();	
			var stickermax = $(document).outerHeight() - $(".footer").outerHeight() - s.outerHeight() - 40; //40 value is the total of the top and bottom margin
			$(window).scroll(function() {
				var windowpos = $(window).scrollTop();
				if (windowpos >= pos.top && windowpos < stickermax) {
					s.attr("style", ""); //kill absolute positioning
					s.addClass("stick"); //stick it
				} else if (windowpos >= stickermax) {
					s.removeClass(); //un-stick
					s.css({position: "absolute", top: stickermax + "px"}); //set sticker right above the footer
					
				} else {
					s.removeClass(); //top of page
				}
			});
		});			
		
	});
</script>

<?php include 'includes/constant/nav.inc.php'; ?>

<h1>Get A Quote Now!</h1>

<div class="container_left">
	<div id="accordion">
	<?php echo load_product_details(); //show product details HTML which is generated by the function in config.inc.php ?>
	</div>
</div>
<div class="container_right">
	<!-- quote form -->
	<div id="sticker">
		<h2>Get A Quote Now!</h2>
		<p><small>* required field</small></p>
		<form action="thanks.php" method="post" name="form" id="quote_form">
			<!-- jquery ui auto-complete for club -->
			<div class="ui-widget">
			<label for="club">Clubs*: </label>
			<input id="club" name="club">
			</div>
			<!-- jquery ui auto-complete for shaft -->
			<div class="ui-widget">
			<label for="shaft">Shafts*: </label>
			<input id="shaft" name="shaft">
			</div>
			<p><label>Quantity*: </label>
			<input type="text" id="quantity" name="quantity" /></p>
			<p><label>Full Name*: </label>
			<input type="text" id="customer" name="customer" /></p>
			<p><label>Email Address*: </label>
			<input type="text" id="email" name="email" /></p>
			<p><label>Comment: </label>
			<textarea name="comment" id="comment" rows="3" cols="54"></textarea></p>
			<p class="subscribe">
			<input type="hidden" name="subscribe" velue="0">
			<input type="checkbox" id="subscribe" name="subscribe" value="1" checked>&nbsp;&nbsp;Subscribe Newsletter</p>
			<p><button type="submit" class="submit button orange" value="submit">Get A Quote!</button></p>
		</form>
	</div>
</div>

<?php include('includes/constant/footer.inc.php'); ?>